#
# Licensed Materials - Property of IBM
#
# (c) Copyright IBM Corp. 2024
#
# The source code for this program is not published or otherwise
# divested of its trade secrets, irrespective of what has been
# deposited with the U.S. Copyright Office
#

FROM oso-harmonzie-plugins:latest

USER 0
ENV DEBUG=true
RUN microdnf --assumeyes \
        --setopt=install_weak_deps=0 \
        --disablerepo='*' \
        --enablerepo=ubi-9-baseos-rpms \
        --enablerepo=ubi-9-appstream-rpms \
        install \
            openssh-server vim sudo procps-ng \
    && microdnf clean all \
    && ssh-keygen -A \
    && chown -R 1001:0 /etc/ssh \
    && chmod 0755 /etc/ssh/sshd_config \
    && install --mode 0644 --owner 1001 --group 0 $(mktemp) ${HOME}/.ssh/authorized_keys \
    && useradd --uid 1001 --gid 0 --home-dir ${HOME} --no-create-home appuser \
    && echo 'appuser ALL=(ALL) NOPASSWD: ALL' | EDITOR='tee -a' visudo

USER 1001
