#
# Licensed Materials - Property of IBM
#
# (c) Copyright IBM Corp. 2024
#
# The source code for this program is not published or otherwise
# divested of its trade secrets, irrespective of what has been
# deposited with the U.S. Copyright Office
#

[build-system]
requires = [
    "cython >= 3",
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "ibm-harmonize-oso-plugins"
dynamic = ["version"]
requires-python = ">= 3.12"


[project.optional-dependencies]
dependencies = [
    "cryptography",
    "flask",
    "flask-restx",
    "gunicorn",
    "requests",
    "supervisor",
    "urllib3",
]
dev = [
    "docker",
    "packaging",
    "pip-tools",
    "pre-commit",
    "podman",
]
test = [
    "coverage",
    "pip",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "requests-mock",
    "requests-toolbelt",
]

[tool.isort]
profile = "black"
filter_files = true
known_first_party = [
    "oso-harmonize-plugins",
    "tests.common",
]

[tool.commitizen]
name = "cz_conventional_commits"
version_provider = "pep621"
update_changelog_on_bump = true

[tool.pytest.ini_options]
pythonpath = "."
addopts = "--import-mode=importlib --cov=oso_harmonize_plugins --cov-report=xml:/tests/results/coverage.xml --junit-xml=/tests/results/junit.xml"

[oso-internal.tooling.versions]
direnv = "2.34.0"
rust = "1.76.0"
