events {} 
stream {
    upstream grpc_servers1 {
        server localhost:10876 max_fails=3 fail_timeout=10s;
        server localhost:11876 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 9876 ;
	
        proxy_pass grpc_servers1;
	proxy_next_upstream on;
    }
}

