##############################################################################
#
# Licensed Materials - Property of IBM
#
# (c) Copyright IBM Corp. 2024
#
# The source code for this program is not published or otherwise
# divested of its trade secrets, irrespective of what has been
# deposited with the U.S. Copyright Office
#
##############################################################################
[supervisord]
nodaemon=true

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:frontend_plugin]
directory=/app-root
command=sh -c 'gunicorn -w 1 --bind unix:/tmp/ipc.sock  oso_harmonize_plugins.frontend_plugin.frontend_plugin_server:app'
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
stopsignal=QUIT

[program:nginx]
command=sh -c '/app-root/nginx/nginx.sh'
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
stopsignal=QUIT

[program:sshd]
command=sh -c '/usr/sbin/sshd -D'
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
autostart=%(ENV_DEBUG)s
stopsignal=QUIT
