version: '3.1'

services:
  vault-cold-bridge:
    image: registry.control23.dap.local/oso/vault-cold-bridge@sha256:
    environment:
      # This must be same as VAULT_ID below
      Vault__Ids__0: 
      Passphrase: "{{EMPTY}}"
    ports:
      - 9999:8080
   
  vault-releases:
    image: registry.control23.dap.local/oso/vault-releases@sha256:
    depends_on:
      - vault-cold-bridge

    environment:
      PLATFORM: mock
      MOCK_PHRASE: ibmosocold

      # This is the notary public key if it's mock
      TRUSTED_SIG: user:
      VAULT_ID: 

      # This comes from the docker container that is spun up above. If it's normal vault, then it would be API end point.
      HARMONIZE_CORE_ENDPOINT: http://vault-cold-bridge:8080/internal/v1 

networks:
  default:
